INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_GNURADIO_CYBERRADIO gnuradio-cyberradio)

FIND_PATH(
    GNURADIO_CYBERRADIO_INCLUDE_DIRS
    NAMES CyberRadio/api.h
    HINTS $ENV{GNURADIO_CYBERRADIO_DIR}/include
        ${PC_GNURADIO_CYBERRADIO_INCLUDEDIR}
    PATHS /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    GNURADIO_CYBERRADIO_LIBRARIES
    NAMES gnuradio-CyberRadio
    HINTS $ENV{GNURADIO_CYBERRADIO_DIR}/lib
        ${PC_GNURADIO_CYBERRADIO_LIBDIR}
    PATHS /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)
MESSAGE(STATUS "---> ${GNURADIO_CYBERRADIO_LIBRARIES} : ${GNURADIO_CYBERRADIO_INCLUDE_DIRS}")

if(GNURADIO_CYBERRADIO_INCLUDE_DIRS AND GNURADIO_CYBERRADIO_LIBRARIES)
  set(GNURADIO_CYBERRADIO_FOUND TRUE CACHE INTERNAL "gnuradio-CyberRadio found")
  message(STATUS "Found gnuradio-CyberRadio: ${GNURADIO_CYBERRADIO_INCLUDE_DIRS}, ${GNURADIO_CYBERRADIO_LIBRARIES}")
else(GNURADIO_CYBERRADIO_INCLUDE_DIRS AND GNURADIO_CYBERRADIO_LIBRARIES)
  set(GNURADIO_CYBERRADIO_FOUND FALSE CACHE INTERNAL "gnuradio-CyberRadio found")
  message(STATUS "gnuradio-CyberRadio not found.")
endif(GNURADIO_CYBERRADIO_INCLUDE_DIRS AND GNURADIO_CYBERRADIO_LIBRARIES)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GNURADIO_CYBERRADIO DEFAULT_MSG GNURADIO_CYBERRADIO_LIBRARIES GNURADIO_CYBERRADIO_INCLUDE_DIRS)
MARK_AS_ADVANCED(GNURADIO_CYBERRADIO_LIBRARIES GNURADIO_CYBERRADIO_INCLUDE_DIRS)
